version: '3.8'

services:
  minio:
    restart: always
    image: minio/minio
    container_name: datalake_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  warehouse:
    image: postgres:13
    container_name: warehouse_postgres
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password123"
      POSTGRES_DB: "mie_db"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  data-app:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: processing_app
    volumes:
      - .:/app 
    ports:
      - "8501:8501"
      - "8888:8888"
    depends_on:
      - minio
      - warehouse
    environment:
      - MINIO_ENDPOINT=minio:9000
      - DB_HOST=warehouse